# Action 的名字
name: Github Action学习

# 触发条件
on:
  # 收到 push 后执行任务
  push:
    branches:
      - main
      - master
  # 手动点击运行
  workflow_dispatch:

# 环境变量
env:
  VERSION: 1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 显示环境变量
      - name: Show Version
        run: echo "Code version is ${{ env.VERSION }}"

      # 克隆当前代码
      - name: Checkout
        uses: actions/checkout@v2

      # 查看当前目录中的文件与文件夹
      - name: List file
        run: |
          ls -alh

      # 运行主要程序
      - name: Run Program
        run: |
          echo "Start Program"
          echo "GITHUB_REPOSITORY_OWNER_ID ${{github.repository_owner}}"
          echo "aaa" >> Readme

      # 上传当前代码
      - name: Upload code
        run: |
          git config --global user.name "WHG555"
          git config --global user.email "whghcyx@outlook.com"
          git add .
          git commit -m "feat: Update code"
          git push https://${{secrets.TODAY_GITHUB_KEY}}@github.com/${{ github.repository }}.git HEAD:master
        env:
          GH_TOKEN: ${{ secrets.TODAY_GITHUB_KEY }}
    
